# Starting off with OpenSSL workflow file: We need to build OpenSSL too...

name: Windows tests

on: [pull_request, push]

permissions:
  contents: read

jobs:
  cygwin:
    # Run a job for each of the specified target architectures:
    strategy:
      matrix:
        os:
          - windows-2019
#          - windows-2022
        platform:
          - arch: win64
            config: -DOQS_ALGS_ENABLED=STD
#          - arch: win32
#            config: --strict-warnings no-fips enable-quic
    runs-on: ${{matrix.os}}
    env:
      CYGWIN_NOWINPATH: 1
      SHELLOPTS: igncr
      MAKE_PARAMS: -j 4
    steps:
#    - uses: ilammy/msvc-dev-cmd@v1
#      with:
#        arch: ${{ matrix.platform.arch }}
    - uses: cygwin/cygwin-install-action@master
      with:
         packages: perl git make cmake gcc-core ninja python3 python3-pip python3-pytest
# Disabled as cygwin seems to cause PATH problems
#    - uses: actions/checkout@v3
    - name: Check repo
      run: cygcheck -V
#    - name: find libcrypto
#      run: bash -c "find /cygdrive/c -name 'libcrypto*' -print"
    - name: Full cygcheck debug
      run: cygcheck -s -v -r -h 
    - name: Clone repo 
      run: bash -c "pwd && git clone --branch ${{ github.ref_name }} --depth 1 https://github.com/${{ github.repository }}.git"
    - name: Full build
      run: bash -c "pwd && cd oqs-provider && echo 'PATH = $PATH' && ls && ./scripts/fullbuild.sh"
    - name: Run tests
      run: bash scripts/runtests.sh -V

