# Starting off with OpenSSL workflow file: We need to build OpenSSL too...

name: Windows tests

on: [pull_request, push]

permissions:
  contents: read

jobs:
  cygwin:
    # Run a job for each of the specified target architectures:
    strategy:
      matrix:
        os:
          - windows-2019
#          - windows-2022
        platform:
          - arch: win64
            config: -DOQS_ALGS_ENABLED=STD
#          - arch: win32
#            config: --strict-warnings no-fips enable-quic
    runs-on: ${{matrix.os}}
    env:
      CYGWIN_NOWINPATH: 1
      SHELLOPTS: igncr
      MAKE_PARAMS: -j 4
    steps:
    - uses: cygwin/cygwin-install-action@master
      with:
         packages: perl git make gcc-core libssl-devel-3.0.8-0.1 openssl-3.0.8-0.1 
# Disabled as cygwin seems to cause PATH problems
#    - uses: actions/checkout@v3
    - name: Clone repo 
      run: bash -c "pwd && git clone --branch ${{ github.ref_name }} --depth 1 https://github.com/${{ github.repository }}.git"
    - name: Full build
      run: bash -c "pwd && cd oqs-provider && echo 'PATH = $PATH' && ls && ./scripts/fullbuild.sh"
    - name: Run tests
      run: bash scripts/runtests.sh -V

